modLoader="javafml"
loaderVersion="[54,)"
license="MIT"

[[mods]]
modId="examplemod"
version="1.0.0"
displayName="CSCE466 ImGui Mod"
description='''
Forge 1.21.4 mod with ImGui renderer.
'''

[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[54.1.16,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.21.4,1.21.5)"
ordering="NONE"
side="BOTH"